services:
  ai_agent:
    image: ${ECR_REGISTRY}/elsie-ai-agent:latest
    ports:
      - "8000:8000"
    env_file:
      - .env
    environment:
      - PORT=8000
      - GEMMA_API_KEY=${GEMMA_API_KEY}
      - DB_HOST=elsiebrain_db
      - DB_NAME=${DB_NAME}
      - DB_USER=${DB_USER}
      - DB_PASSWORD=${DB_PASSWORD}
      - DB_PORT=5432  # Internal port remains 5432
    volumes:
      - ./ai_agent:/app
    networks:
      - elsie_network
    depends_on:
      elsiebrain_db:
        condition: service_healthy
    healthcheck:
      test: ["CMD", "curl", "-f", "http://localhost:8000/"]
      interval: 30s
      timeout: 10s
      retries: 3

  discord_bot:
    image: ${ECR_REGISTRY}/elsie-discord-bot:latest
    env_file:
      - .env
    environment:
      - DISCORD_TOKEN=${DISCORD_TOKEN}
      - AI_AGENT_URL=http://ai_agent:8000
      - GEMMA_API_KEY=${GEMMA_API_KEY}
    volumes:
      - ./discord_bot:/app
    networks:
      - elsie_network
    depends_on:
      ai_agent:
        condition: service_healthy

  db_populator:
    build:
      context: ./db_populator
      dockerfile: Dockerfile
    container_name: elsiebrain_populator
    env_file:
      - .env
    environment:
      - DB_HOST=elsiebrain_db
      - DB_NAME=${DB_NAME}
      - DB_USER=${DB_USER}
      - DB_PASSWORD=${DB_PASSWORD}
      - DB_PORT=5432  # Internal port remains 5432
      - WIKI_UPDATE_INTERVAL=3600  # Update every hour
    networks:
      - elsie_network
    depends_on:
      elsiebrain_db:
        condition: service_healthy
    restart: unless-stopped  # Keep running unless manually stopped

volumes:
  elsiebrain_data:
    driver: local

networks:
  elsie_network:
    driver: bridge 