version: '3.8'

services:
  elsiebrain_db:
    image: postgres:15
    container_name: elsiebrain_postgres_dev
    environment:
      - POSTGRES_DB=elsiebrain
      - POSTGRES_USER=elsie
      - POSTGRES_PASSWORD=elsie123
    ports:
      - "5433:5432"
    volumes:
      - elsiebrain_dev_data:/var/lib/postgresql/data
    networks:
      - elsie_dev_network
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U elsie -d elsiebrain"]
      interval: 10s
      timeout: 5s
      retries: 5
    restart: unless-stopped

volumes:
  elsiebrain_dev_data:
    driver: local

networks:
  elsie_dev_network:
    driver: bridge
    external: false 